# Generated by Django 6.0.2 on 2026-02-25 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asset',
            new_name='Item',
        ),
    ]
