# Generated by Django 6.0.2 on 2026-02-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_item_date_added_remove_item_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
