# Generated by Django 6.0.2 on 2026-03-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_item_location_item_supplier_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='location',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.CharField(default='Not Provided', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='not_provided@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
