# Generated by Django 6.0.2 on 2026-03-16 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_item_created_at_alter_userprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='order_date',
        ),
    ]
