# Generated by Django 6.0.2 on 2026-05-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_userprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
